Sprint 6
SberKotlinSchool/Sprint-6 pull request #12
Opened 2022-11-07 19:22 UTC by TheWeaklessOne

2022-11-07 19:24 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/617/

2022-11-07 19:57 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/618/

2022-11-08 08:07 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/623/

2022-11-08 08:10 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/624/

2022-11-08 08:11 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/625/

2022-11-08 21:07 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/632/

2022-11-09 14:24 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/637/

2022-11-21 11:26 UTC, SharikTLT commented
mvc еще не готов?

2022-12-07 12:55 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/1218/

2022-12-07 13:36 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/1219/

2022-12-11 16:00 UTC, SharikTLT commented on spring-mvc/pom.xml
> +		<java.version>17</java.version>
на дженкинсе 1.8 джава, по этому проект не компилится

2022-12-11 16:04 UTC, SharikTLT commented on spring-mvc/pom.xml
> +		<java.version>17</java.version>
![изображение](https://user-images.githubusercontent.com/2510580/206914401-5e194545-c390-45bb-bf2d-f374c9affa2b.png)
но с достаточной версии джавы собирается

2022-12-11 16:06 UTC, SharikTLT approved these changes
spring-mvc выполнено без замечаний

2024-02-15 12:36 UTC, closed without merging