sprint 6
SberKotlinSchool/Sprint-6 pull request #28
Opened 2022-11-22 09:03 UTC by stasyanich

2022-11-22 09:04 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/937/

2022-11-22 11:30 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/940/

2022-11-22 13:23 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/941/

2022-12-17 15:14 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/1328/

2022-12-17 16:56 UTC, SharikTLT reviewed
spring-mvc выполнено без замечаний

2025-12-26 14:08 UTC, closed without merging