Все задачи sprint-6
SberKotlinSchool/Sprint-6 pull request #64
Opened 2023-11-25 17:15 UTC by ShedowSith

Нужна помощь с двумя тестами: getRecord и changeRecord класса AddressBookControllerTest, находятся в выключенном состоянии

2023-11-25 17:17 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/509/

2023-11-27 16:01 UTC, SharikTLT commented on spring-mvc/src/main/kotlin/ru/shadowsith/addressbook/controllers/AddressBookApiController.kt
> +        produces = [MediaType.APPLICATION_JSON_VALUE]
что бы не дублировать у каждого метода, можно на уровне @RequestMapping аннотации задать consumes и produces

2023-11-27 17:11 UTC, SharikTLT commented on spring-mvc/src/test/kotlin/ru/shadowsith/addressbook/controllers/AddressBookControllerTest.kt
> +            .flashAttr("record", record)
этот метод добавляет атрибут входящего запроса
следует подключить через @Autowired интерфейс репозитория и прежде чем делать вызов perform, положить в репозиторий тестовый record + в запросе указать в url значение record.guid, что бы контроллер сделал поиск по guid именно этой тестовой записи

2023-11-27 17:12 UTC, SharikTLT commented on spring-mvc/src/test/kotlin/ru/shadowsith/addressbook/controllers/AddressBookControllerTest.kt
> +        mockMvc.perform(get("/app/dd375830-95b7-4c94-92ec-c9cd50f75d46/delete"))
тут так же рекомендуется через репозиторий создать сперва тестовую запись, выполнить запрос и проверить, что запись из репозитория удалена

2023-11-27 17:13 UTC, SharikTLT commented on spring-mvc/src/test/kotlin/ru/shadowsith/addressbook/controllers/AddressBookControllerTest.kt
> +        mockMvc.perform(post("/app/dd375830-95b7-4c94-92ec-c9cd50f75d46/edit")
тут по аналогии стоит сперва в репозиторий добавить тестовую запись с данным конкретным guid

2023-11-27 17:14 UTC, SharikTLT commented
по sprig mvc осталось поправить тест через mockMvc + тесты через restTemplate

- [ ] поправить тесты mockMvc
- [ ] создать тесты через restTemplate

2023-11-30 12:26 UTC, SberKotlinSchool commented on spring-dependency-injection/src/main/kotlin/ru/sber/services/SeveralServices.kt
> +        return arrayListOf(FirstServiceImpl(), SecondServiceImpl())
При починке теста severalBeanInjectionService should have two dependencies класс SeveralServicesConfig изменять нельзя
Обрати внимание на тип переменной services в класне SeveralBeanInjectionService, может он натолкнет на мысль, почему мы в тесте получаем не то, что ожидаем

2023-12-01 06:58 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/581/

2023-12-01 13:26 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/587/

2023-12-01 13:26 UTC, SharikTLT commented
spring-mvc выполнено с незначительными комментариями

2025-05-19 19:18 UTC, closed without merging