Hw 5
SberKotlinSchool/Sprint-6 pull request #69
Opened 2023-11-26 19:55 UTC by aperfilyev

2023-11-26 19:57 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/528/

2023-11-26 20:22 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/529/

2023-11-26 20:42 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/530/

2023-11-27 06:23 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/533/

2023-11-27 17:24 UTC, SharikTLT reviewed
spring mvc выполнено без замечаний

2023-11-30 13:30 UTC, SberKotlinSchool commented on spring-java-config/src/main/kotlin/ru/sber/config/AnotherServicesConfig.kt
> +    fun fourthService(): FourthService {
Попробуй иначе, например, посмотреть на то, в каком пакете мы ищем нужные нам бины

2023-11-30 15:57 UTC, aperfilyev commented on spring-java-config/src/main/kotlin/ru/sber/config/AnotherServicesConfig.kt
> +    fun fourthService(): FourthService {
готово

2023-12-05 19:51 UTC, closed without merging