Sprint-6 homework [jdkEdge:spring-mvc]
SberKotlinSchool/Sprint-6 pull request #73
Opened 2023-12-01 16:21 UTC by DOKL57

2023-12-01 16:22 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/589/

2023-12-01 16:53 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/591/

2023-12-01 16:54 UTC, shariktlt-devops requested changes
:no_entry: build failed with modules spring-mvc, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/592/

2023-12-01 16:59 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/594/

2023-12-01 17:04 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/KotlinSchool/job/PR_Builder/595/

2023-12-03 17:35 UTC, SharikTLT commented on spring-mvc/src/main/kotlin/com/dokl57/springmvc/config/ApplicationConfiguration.kt
> +@ServletComponentScan("com/dokl57/springmvc/servlet", "com.dokl57.springmvc.filter")
Первый вариант через слеш некорректный.
атрибут basePackage для поиска зависимостей требует второй вариант.

2023-12-03 17:37 UTC, SharikTLT reviewed
spring-mvc выполнено без замечаний

2024-02-15 19:15 UTC, closed without merging